<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <AssemblyName>GestionQ.CajaPOS</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <OutputType>WinExe</OutputType>
    <UseWindowsForms>True</UseWindowsForms>
    <TargetFramework>netcoreapp9.0</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>11.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="GestionQ.Domain">
      <HintPath>C:\GestionQ\app_cajapos\GestionQ.Domain.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.EntityFrameworkCore">
      <HintPath>C:\GestionQ\app_cajapos\Microsoft.EntityFrameworkCore.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.EntityFrameworkCore.Relational">
      <HintPath>C:\GestionQ\app_cajapos\Microsoft.EntityFrameworkCore.Relational.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.EntityFrameworkCore.Sqlite">
      <HintPath>C:\GestionQ\app_cajapos\Microsoft.EntityFrameworkCore.Sqlite.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.Extensions.Identity.Stores">
      <HintPath>C:\GestionQ\app_cajapos\Microsoft.Extensions.Identity.Stores.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.EntityFrameworkCore.Abstractions">
      <HintPath>C:\GestionQ\app_cajapos\Microsoft.EntityFrameworkCore.Abstractions.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
